server.port=8080
#spring.data.mongodb.uri=mongodb+srv://CastMyGame:Maxorion614418@reps.risjic2.mongodb.net/REPS?retryWrites=true&w=majority

spring.config.import=sm://

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=REPS.DMS
spring.mail.password=wuwxupmniesznfkv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.task.scheduling.pool.size=20
spring.data.mongodb.uri=mongodb+srv://repsdiscipline:123abc@repsdevdb.xgrmfbb.mongodb.net/repsdevdb?retryWrites=true&w=majority

#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# === Google OAuth2 Client Configuration ===

spring.security.oauth2.client.registration.google.client-id=1008422747240-bu8c065aadkp6g9ghpgd5f7f9qhkcc7t.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

