auth.sso.google.redirect-url=https://www.repsdiscipline.com

spring.data.mongodb.uri=${sm://reps-prod-mongodb-uri}

stripe.secret.key=${sm://stripe-live-secret-key}
stripe.webhook.secret=${sm://stripe-live-webhook-secret}
stripe.checkout.success-url=https://www.repsdiscipline.com/checkout/success
stripe.checkout.cancel-url=https://www.repsdiscipline.com/checkout/cancel

spring.security.oauth2.client.registration.google.client-id=${sm://google_oauth_client_id}
spring.security.oauth2.client.registration.google.client-secret=${sm://google_oauth_client_secret}
spring.security.oauth2.client.registration.google.scope=openid, email, profile, https://www.googleapis.com/auth/gmail.send
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com