spring.config.import=sm://

auth.sso.google.redirect-url=https://repsdev.vercel.app

spring.data.mongodb.uri=${sm://reps-dev-mongodb-uri}

stripe.secret.key=${sm://stripe_key}
stripe.webhook.secret=${sm://stripe_webhook_key}
stripe.checkout.success-url=https://repsdev.vercel.app/checkout/success
stripe.checkout.cancel-url=https://repsdev.vercel.app/checkout/cancel

spring.mail.password=${sm://gmail_password}

spring.security.oauth2.client.registration.google.client-id=${sm://google_oauth_client_id}
spring.security.oauth2.client.registration.google.client-secret=${sm://google_oauth_client_secret}
spring.security.oauth2.client.registration.google.scope=openid, email, profile, https://www.googleapis.com/auth/gmail.send
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com